{% set data = load_setup_py_data() %}

package:
  name: vcf2tsvpy
  version: {{ data.get('version') }}

source:
  path: ../..

build:
  number: 0
  noarch: python

requirements:
  build:
    - curl
    - unzip
    - tar
    - python
  run:
    - python
    - numpy
    - cyvcf2
    - pip

test:
  commands:
    - vcf2tsvpy --version

about:
  home: {{ data.get('url') }}
  license: {{ data.get('license') }}
  summary: {{ data.get('description') }}
